<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="markingmate" nsURI="markingmate" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="Exam">
    <eStructuralFeatures xsi:type="ecore:EReference" name="questions" upperBound="-1"
        eType="#//Question" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" upperBound="-1"
        eType="#//Student" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Question">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answers" upperBound="-1"
        eType="#//Answer" transient="true" eOpposite="#//Answer/question"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Student">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="answers" upperBound="-1"
        eType="#//Answer" containment="true" eOpposite="#//Answer/student"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Answer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="student" eType="#//Student"
        transient="true" eOpposite="#//Student/answers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="question" eType="#//Question"
        resolveProxies="false" eOpposite="#//Question/answers"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feedback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="marks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
</ecore:EPackage>
