# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
          format: 'DD.MM.YYYY HH:mm'
    - name: Build with Ant
      run: ant -noinput -buildfile io.dimitris.markingmate/build.xml
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Build ${{ steps.time.outputs.time }}"
          prerelease: false
          files: |
            io.dimitris.markingmate/dist/MarkingMate.dmg
            io.dimitris.markingmate/dist/MarkingMate.zip
